{{- $fullName := include "decidim-helm.fullname" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" $fullName "config" }}
  labels:
    {{- include "decidim-helm.labels" . | nindent 4 }}
data:
  RAILS_ENV: production
  RAILS_SERVE_STATIC_FILES: "true"
  APP_NAME: "decidim_sen"
  WEB_CONCURRENCY: "0"
  CACHE_ASSETS: "true"
  RAILS_LOG_TO_STDOUT: 'true'
