{{- if .Values.sdqAutoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "decidim-helm.fullname" . }}
  labels:
    {{- include "decidim-helm.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "decidim-helm.webFullname" . }}
  minReplicas: {{ .Values.sdqAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.sdqAutoscaling.maxReplicas }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.sdqAutoscaling.stabilizationWindowSeconds }}
  metrics:
    {{- if .Values.sdqAutoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.sdqAutoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.sdqAutoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.sdqAutoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
