{{- $fullName := include "decidim-helm.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "decidim-helm.webFullname" . }}
  labels:
    {{- include "decidim-helm.webLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: {{ include "decidim-helm.webFullname" . }}
  {{- if not .Values.webAutoscaling.enabled }}
  replicas: {{ .Values.deployment.web.replicaCount }}
  {{- end }}
  template:
    metadata:
      {{- with .Values.deployment.web.spec.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "decidim-helm.webSelectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.deployment.web.spec.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "decidim-helm.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.deployment.web.spec.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.web.spec.containers.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          startupProbe:
            httpGet:
              path: {{ default "/health_check" .Values.deployment.web.spec.containers.startupProbe.path }}
              port: {{ .Values.deployment.web.spec.containers.port }}
            initialDelaySeconds: {{ .Values.deployment.web.spec.containers.startupProbe.initialDelaySeconds }}
            failureThreshold: {{ .Values.deployment.web.spec.containers.startupProbe.failureThreshold }}
            periodSeconds: {{ .Values.deployment.web.spec.containers.startupProbe.periodSeconds }}
          resources:
            {{- toYaml .Values.deployment.web.spec.containers.resources | nindent 12 }}
          ports:
            - containerPort: {{ .Values.webContainerPort }}
          env:
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          envFrom:
            - configMapRef:
                name: {{ printf "%s-%s" $fullName "config" }}
            - secretRef:
                name: {{ printf "%s-%s" $fullName "secrets" }}
      {{- with .Values.deployment.web.spec.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.web.spec.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.web.spec.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
